apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    acme.cert-manager.io/disable-challenge-http01-self-check: "true" 
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: raslenm39@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - http01:
        ingress:
          class: nginx